# Generated by Django 4.2.28 on 2026-02-25 07:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('muscle_group', models.CharField(choices=[('chest', 'Petto'), ('back', 'Schiena'), ('shoulders', 'Spalle'), ('biceps', 'Bicipiti'), ('triceps', 'Tricipiti'), ('legs', 'Gambe'), ('glutes', 'Glutei'), ('abs', 'Addome'), ('calves', 'Polpacci'), ('forearms', 'Avambracci'), ('full_body', 'Full Body')], max_length=20, verbose_name='Gruppo muscolare')),
                ('description', models.TextField(blank=True, verbose_name='Descrizione')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_exercises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Esercizio',
                'verbose_name_plural': 'Esercizi',
                'ordering': ['muscle_group', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome scheda')),
                ('description', models.TextField(blank=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Attiva')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scheda',
                'verbose_name_plural': 'Schede',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlannedExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_sets', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Serie obiettivo')),
                ('target_reps', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Ripetizioni obiettivo')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordine')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Note')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.exercise')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_exercises', to='gym.workoutplan')),
            ],
            options={
                'verbose_name': 'Esercizio in scheda',
                'verbose_name_plural': 'Esercizi in scheda',
                'ordering': ['order'],
                'unique_together': {('plan', 'exercise')},
            },
        ),
        migrations.CreateModel(
            name='ExerciseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('sets', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Serie eseguite')),
                ('reps', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Ripetizioni eseguite')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Carico (kg)')),
                ('one_rm', models.DecimalField(decimal_places=2, editable=False, max_digits=6, verbose_name='Massimale teorico (kg)')),
                ('notes', models.TextField(blank=True, verbose_name='Note sessione')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='gym.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log allenamento',
                'verbose_name_plural': 'Log allenamenti',
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['user', 'exercise', '-date'], name='gym_exercis_user_id_d5551d_idx')],
            },
        ),
    ]
