# Generated by Django 4.2.28 on 2026-04-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workoutplan',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Scheda', 'verbose_name_plural': 'Schede'},
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordine'),
        ),
    ]
