# Generated by Django 4.2.28 on 2026-07-25 16:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_alter_workoutplan_options_workoutplan_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='is_bodyweight',
            field=models.BooleanField(default=False, verbose_name='A corpo libero'),
        ),
        migrations.AlterField(
            model_name='exerciselog',
            name='one_rm',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=6, null=True, verbose_name='Massimale teorico (kg)'),
        ),
        migrations.AlterField(
            model_name='exerciselog',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Carico (kg)'),
        ),
    ]
