# Generated by Django 4.2.28 on 2026-08-01 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gym', '0003_exercise_is_bodyweight_alter_exerciselog_one_rm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome cartella')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordine')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_folders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cartella',
                'verbose_name_plural': 'Cartelle',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='gym.planfolder', verbose_name='Cartella'),
        ),
    ]
