# Generated by Django 6.0.7 on 2026-08-09 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_planfolder_workoutplan_folder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('plan_name', models.CharField(max_length=100, verbose_name='Nome scheda')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='gym.workoutplan', verbose_name='Scheda')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sessione di allenamento',
                'verbose_name_plural': 'Sessioni di allenamento',
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['user', '-date'], name='gym_workout_user_id_9f27f6_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'date', 'plan_name'), name='unique_session_per_plan_per_day')],
            },
        ),
    ]
