# Generated by Django 6.0.7 on 2026-08-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0005_workoutsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsession',
            name='is_free',
            field=models.BooleanField(default=False, verbose_name='Allenamento libero'),
        ),
    ]
