# Generated by Django 6.0.7 on 2026-08-30 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0006_workoutsession_is_free'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='video_added_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Video aggiunto il'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='video_added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_exercise_videos', to=settings.AUTH_USER_MODEL, verbose_name='Video aggiunto da'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='youtube_video_id',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='ID video YouTube'),
        ),
    ]
