# Generated by Django 6.0 on 2026-10-03 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0009_userpreferences'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='standard_key',
            field=models.CharField(blank=True, help_text='Chiave nel dizionario STANDARDS per il benchmark (es. bench_press). Lascia vuoto per esercizi senza benchmark.', max_length=30, null=True, verbose_name='Chiave standard di forza'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_weight', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Peso corporeo (kg)')),
                ('sex', models.CharField(blank=True, choices=[('M', 'Uomo'), ('F', 'Donna')], max_length=1, null=True, verbose_name='Sesso')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Data di nascita')),
                ('training_level', models.CharField(choices=[('beginner', 'Principiante'), ('novice', 'Novizio'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzato'), ('elite', 'Elite')], default='beginner', max_length=15, verbose_name='Livello di allenamento')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profilo fisico',
                'verbose_name_plural': 'Profili fisici',
            },
        ),
    ]
