# Generated by Django 6.0 on 2026-10-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0013_populate_more_standard_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Maschio'), ('F', 'Femmina')], max_length=1, null=True, verbose_name='Sesso'),
        ),
    ]
