# Generated by Django 6.0 on 2026-10-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0014_userprofile_sex_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dumbbell_weight_mode',
            field=models.CharField(choices=[('auto', 'Automatico (deduci dai miei log)'), ('per_dumbbell', 'Peso di un singolo manubrio'), ('total', 'Somma dei due manubri')], default='auto', help_text='Negli esercizi con due manubri (panca, curl, alzate...) il carico che registri è quello di un manubrio o la somma dei due? Con "Automatico" lo deduciamo confrontando i tuoi log coi manubri e col bilanciere.', max_length=12, verbose_name='Peso dei manubri nei log'),
        ),
    ]
